version: '3.8'
services:
  runner:
    build: .
    image: iacutone/elpais_rss:latest
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - EL_PAIS_RSS_URL=${EL_PAIS_RSS_URL}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - MIX_ENV=prod
