service: elpais_rss
image: iacutone/elpais_rss
servers: 
  - "5.161.60.147"

registry:
  username: iacutone
  password:
    - DOCKER_REGISTRY_PASSWORD

ssh:
  user: root

builder:
  arch: amd64

env:
  secret:
    - AWS_ACCESS_KEY
    - AWS_SECRET_KEY
    - EL_PAIS_RSS_URL
    - MAILCHIMP_API_KEY
    - GOOGLE_GEMINI_API_KEY 
